### ISSUE TITLE
Weekly Digest not being generated despite adding app and config.

### ISSUE THREAD

**Issue by samrith-s** [probot/weekly-digest#76]
Hey,

We have a `.github/weekly-digest.yml` present in our repository with the following contents:
```yaml
# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: sun
canPublishIssues: false
canPublishPullRequests: true
canPublishContributors: true
canPublishStargazers: false
canPublishCommits: true
```

And no weekly digest is generated. I have added the app and all, but it doesn't generate anything. It works on another repo which doesn't have a config file.

Am I missing something? Thanks in advance!
